(function(){
"use strict";

// dashboard_data.js is generated by src/export_dashboard_data.py.
// If it is missing, show a short message instead of a blank page.
var DATA = window.__DASHBOARD_DATA__;
window.__DASHBOARD_DATA_MISSING__ = !DATA || !DATA.batches || !DATA.batches.length;
if (window.__DASHBOARD_DATA_MISSING__){
  document.addEventListener("DOMContentLoaded", function(){
    document.querySelector(".app").innerHTML =
      '<div class="empty-state">' +
        '<h1>No dashboard data found</h1>' +
        '<p>This dashboard reads <code>frontend/data/dashboard_data.js</code>, which the Python backend generates -- it isn\u2019t committed by hand.</p>' +
        '<p>From the project root, run:</p>' +
        '<pre>cd src\npython export_dashboard_data.py</pre>' +
        '<p>then reload this page.</p>' +
      '</div>';
  });
  // Empty payload so the stats code below doesn't throw.
  DATA = {
    meta: {generated_at:"", orders_processed:0, batches_ffd:0, batches_optimized:0, batches_saved:0,
           distance_baseline_m:0, distance_optimized_m:0, distance_saved_m:0, improvement_pct:0, runtime_sec:0},
    warehouse: {depot:{location_id:"DEPOT", x:0, y:0}, locations:[], aisles:[], racks:[]},
    batches: []
  };
}
var ALGO_LABELS = {greedy:"Greedy", nearest_neighbor:"Nearest neighbor", two_opt:"2-opt"};
var DEPOT_ID = DATA.warehouse.depot.location_id;

/* ---------------------------------------------------------------- */
/* Stats derived from the loaded results                             */
/* ---------------------------------------------------------------- */

var locationById = {};
DATA.warehouse.locations.forEach(function(l){ locationById[l.location_id] = l; });
locationById[DEPOT_ID] = DATA.warehouse.depot;

var batchesById = {};
DATA.batches.forEach(function(b){ batchesById[b.batch_id] = b; });

function routeLenSeries(algo){
  return DATA.batches.map(function(b){ return b.routes[algo].distance_m; });
}
function sum(arr){ return arr.reduce(function(a,b){return a+b;},0); }
function mean(arr){ return arr.length ? sum(arr)/arr.length : 0; }

var greedyTotal = sum(routeLenSeries("greedy"));
var nnTotal = sum(routeLenSeries("nearest_neighbor"));
var twoOptTotal = sum(routeLenSeries("two_opt"));

var avgRouteLength = mean(routeLenSeries("two_opt"));
var avgPickTimeMin = mean(DATA.batches.map(function(b){ return b.routes.two_opt.time_min; }));

var savedPerBatch = DATA.batches.map(function(b){
  var saved = b.routes.greedy.distance_m - b.routes.two_opt.distance_m;
  var pct = b.routes.greedy.distance_m > 0 ? (saved / b.routes.greedy.distance_m) * 100 : 0;
  return {batch_id:b.batch_id, saved:Math.max(0,saved), pct:pct};
});

var bestBatch = savedPerBatch.reduce(function(best,cur){ return cur.pct > best.pct ? cur : best; }, savedPerBatch[0] || {pct:0});

var aisleCounts = {};
DATA.batches.forEach(function(b){
  b.stops.forEach(function(s){
    aisleCounts[s.aisle] = (aisleCounts[s.aisle]||0) + 1;
  });
});
var aisleList = Object.keys(aisleCounts).sort().map(function(a){ return {aisle:a, count:aisleCounts[a]}; });
var busiestAisle = aisleList.reduce(function(best,cur){ return cur.count > best.count ? cur : best; }, aisleList[0] || {count:0});
var quietestAisle = aisleList.reduce(function(worst,cur){ return cur.count < worst.count ? cur : worst; }, aisleList[0] || {count:0});

/* ---------------------------------------------------------------- */
/* Formatting                                                        */
/* ---------------------------------------------------------------- */

function fmtM(v){ return Math.round(v).toLocaleString() + " m"; }
function fmtPct(v){ return v.toFixed(1) + "%"; }
function esc(s){ return String(s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;"); }
function fmtTime(iso){
  try{
    var d = new Date(iso);
    if (isNaN(d.getTime())) return iso;
    return d.toLocaleString(undefined,{year:"numeric",month:"short",day:"numeric",hour:"2-digit",minute:"2-digit"});
  }catch(e){ return iso; }
}
function $(id){ return document.getElementById(id); }

window.__APP__ = {
  DATA:DATA, ALGO_LABELS:ALGO_LABELS, DEPOT_ID:DEPOT_ID, locationById:locationById, batchesById:batchesById,
  greedyTotal:greedyTotal, nnTotal:nnTotal, twoOptTotal:twoOptTotal,
  avgRouteLength:avgRouteLength, avgPickTimeMin:avgPickTimeMin,
  savedPerBatch:savedPerBatch, bestBatch:bestBatch,
  aisleList:aisleList, busiestAisle:busiestAisle, quietestAisle:quietestAisle,
  fmtM:fmtM, fmtPct:fmtPct, esc:esc, fmtTime:fmtTime, $:$, sum:sum, mean:mean
};
})();
(function(){
"use strict";
var C = window.__APP__;
var DATA=C.DATA, $=C.$, esc=C.esc, fmtM=C.fmtM, fmtPct=C.fmtPct;

function renderKPIs(){
  var m = DATA.meta;
  var pickTimes = DATA.batches.map(function(b){return b.routes.two_opt.time_min;});
  var routeLens = DATA.batches.map(function(b){return b.routes.two_opt.distance_m;});
  var range = function(a, d){ return Math.min.apply(null,a).toFixed(d)+"\u2013"+Math.max.apply(null,a).toFixed(d); };
  var cards = [
    {label:"Orders", value:m.orders_processed, unit:"", note:"in "+m.batches_optimized+" batches"},
    {label:"Batches", value:m.batches_optimized, unit:"", note:m.batches_saved>0 ? m.batches_saved+" fewer than FFD ("+m.batches_ffd+")" : "same as FFD"},
    {label:"Distance saved", value:Math.round(m.distance_saved_m), unit:"m", note:fmtPct(m.improvement_pct)+" vs. baseline"},
    {label:"Baseline distance", value:Math.round(m.distance_baseline_m).toLocaleString(), unit:"m", note:"FFD + greedy"},
    {label:"Optimized distance", value:Math.round(m.distance_optimized_m).toLocaleString(), unit:"m", note:"CP-SAT + 2-opt"},
    {label:"Avg route", value:Math.round(C.avgRouteLength), unit:"m", note:range(routeLens,0)+" m per batch"},
    {label:"Avg est. time", value:C.avgPickTimeMin.toFixed(1), unit:"min", note:range(pickTimes,1)+" min per batch"}
  ];
  $("kpiRow").innerHTML = cards.map(function(c){
    return '<div class="kpi-card">' +
      '<div class="kpi-label">'+esc(c.label)+'</div>' +
      '<div class="kpi-value tnum">'+esc(c.value)+(c.unit?'<span class="unit">'+esc(c.unit)+'</span>':'')+'</div>' +
      '<div class="kpi-note">'+esc(c.note)+'</div>' +
      '</div>';
  }).join("");
}

window.__APP__.renderKPIs = renderKPIs;
})();
(function(){
"use strict";
var C = window.__APP__;
var DATA=C.DATA, $=C.$, esc=C.esc, locationById=C.locationById, DEPOT_ID=C.DEPOT_ID;

var MAP = {viewW:900, viewH:600, marginLeft:60, marginRight:24, marginTop:44, marginBottom:24};

var state = {
  selectedBatchId:null, selectedAlgo:"two_opt",
  fullPath:[], currentStepIndex:0, isPlaying:false, playTimer:null, animFrame:null,
  zoom:1, panX:0, panY:0, isPanning:false, panStart:null
};

function setupMapScale(){
  var wh = DATA.warehouse;
  var minX=wh.depot.x, maxX=wh.depot.x, minY=wh.depot.y, maxY=wh.depot.y;
  wh.locations.forEach(function(l){
    minX=Math.min(minX,l.x); maxX=Math.max(maxX,l.x); minY=Math.min(minY,l.y); maxY=Math.max(maxY,l.y);
  });
  MAP.worldMinX=minX; MAP.worldMaxX=maxX; MAP.worldMinY=minY; MAP.worldMaxY=maxY;
  var plotW = MAP.viewW-MAP.marginLeft-MAP.marginRight, plotH = MAP.viewH-MAP.marginTop-MAP.marginBottom;
  var worldW = Math.max(1e-6, maxX-minX), worldH = Math.max(1e-6, maxY-minY);
  var scale = Math.min(plotW/worldW, plotH/worldH);
  MAP.scale=scale; MAP.offsetX=(plotW-worldW*scale)/2; MAP.offsetY=(plotH-worldH*scale)/2;
}
function worldToScreen(x,y){
  return [MAP.marginLeft+(x-MAP.worldMinX)*MAP.scale+MAP.offsetX, MAP.marginTop+(MAP.worldMaxY-y)*MAP.scale+MAP.offsetY];
}

function renderMapSkeleton(){
  var svg = $("warehouseMap");
  svg.innerHTML =
    '<defs>' +
    '<marker id="arrowBlue" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M2 1L8 5L2 9" fill="none" stroke="var(--blue)" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"></path></marker>' +
    '<marker id="arrowGreen" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M2 1L8 5L2 9" fill="none" stroke="var(--green)" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"></path></marker>' +
    '</defs>' +
    '<g id="viewport"><g id="staticLayer"></g><g id="dynamicLayer"></g><g id="pickerLayer"></g></g>';
  applyViewportTransform();
}

function applyViewportTransform(){
  var g = $("viewport");
  if (g) g.setAttribute("transform","translate("+state.panX+","+state.panY+") scale("+state.zoom+")");
}

function renderStaticMap(){
  var wh = DATA.warehouse, parts=[];
  var plotBottom = MAP.marginTop + (MAP.viewH-MAP.marginTop-MAP.marginBottom);
  wh.aisles.forEach(function(a){
    var x = worldToScreen(a.x, MAP.worldMaxY)[0];
    parts.push('<line x1="'+x.toFixed(1)+'" y1="'+(MAP.marginTop-6).toFixed(1)+'" x2="'+x.toFixed(1)+'" y2="'+plotBottom.toFixed(1)+'" stroke="var(--border)" stroke-width="1"></line>');
    parts.push('<text x="'+x.toFixed(1)+'" y="'+(MAP.marginTop-14).toFixed(1)+'" text-anchor="middle" font-family="var(--font-mono)" font-size="9.5" fill="var(--text-muted)">'+esc(a.label)+'</text>');
  });
  wh.racks.forEach(function(r){
    var y = worldToScreen(MAP.worldMinX, r.y)[1];
    parts.push('<text x="'+(MAP.marginLeft-10).toFixed(1)+'" y="'+y.toFixed(1)+'" text-anchor="end" dominant-baseline="central" font-family="var(--font-mono)" font-size="9.5" fill="var(--text-muted)">'+esc(r.label)+'</text>');
  });
  wh.locations.forEach(function(l){
    var p = worldToScreen(l.x,l.y);
    parts.push('<circle class="bg-dot" data-loc="'+esc(l.location_id)+'" cx="'+p[0].toFixed(1)+'" cy="'+p[1].toFixed(1)+'" r="2.6" fill="var(--text-muted)" opacity="0.35"></circle>');
  });
  var dp = worldToScreen(wh.depot.x, wh.depot.y);
  parts.push('<rect x="'+(dp[0]-9).toFixed(1)+'" y="'+(dp[1]-9).toFixed(1)+'" width="18" height="18" rx="5" fill="var(--blue)"></rect>');
  parts.push('<text x="'+dp[0].toFixed(1)+'" y="'+(dp[1]+1).toFixed(1)+'" text-anchor="middle" dominant-baseline="central" fill="#fff" font-family="var(--font-mono)" font-size="9" font-weight="700">D</text>');
  parts.push('<text x="'+dp[0].toFixed(1)+'" y="'+(dp[1]-16).toFixed(1)+'" text-anchor="middle" font-family="var(--font-mono)" font-size="9.5" fill="var(--text-secondary)">DEPOT</text>');
  $("staticLayer").innerHTML = parts.join("");
}

function initPickerLayer(){
  var pulse = reducedMotion() ? '' : '<animate attributeName="r" values="6;13;6" dur="1.8s" repeatCount="indefinite"></animate><animate attributeName="opacity" values="0.55;0;0.55" dur="1.8s" repeatCount="indefinite"></animate>';
  $("pickerLayer").innerHTML = '<g id="pickerGroup"><circle r="8" fill="none" stroke="var(--blue)" stroke-width="1.6" opacity="0.55">'+pulse+'</circle><circle r="5.5" fill="var(--blue)" stroke="#fff" stroke-width="1.5"></circle></g>';
}

function renderDynamicLayer(){
  var path = state.fullPath, n = path.length;
  var travelIdx = Math.min(state.currentStepIndex, n-1);
  var pts = path.map(function(p){ return worldToScreen(p.x,p.y); });
  var parts=[];
  for (var i=0;i<n-1;i++){
    var traveled = i<travelIdx;
    var cls = traveled ? "var(--green)" : "var(--blue)";
    var marker = traveled ? "url(#arrowGreen)" : "url(#arrowBlue)";
    parts.push('<path d="M '+pts[i][0].toFixed(1)+' '+pts[i][1].toFixed(1)+' L '+pts[i+1][0].toFixed(1)+' '+pts[i+1][1].toFixed(1)+'" fill="none" stroke="'+cls+'" stroke-width="2.2" stroke-linecap="round" marker-end="'+marker+'"></path>');
  }
  for (var j=1;j<n-1;j++){
    var completed = j<=state.currentStepIndex;
    var loc = path[j];
    var fill = completed ? "var(--green)" : "var(--surface)";
    var stroke = completed ? "var(--green)" : "var(--blue)";
    var textFill = completed ? "#06170D" : "var(--text-primary)";
    parts.push('<circle class="stop-node" role="button" tabindex="0" aria-label="Stop '+j+' of '+(n-2)+', location '+esc(loc.location_id)+', '+(completed?'visited':'pending')+'. Press Enter for details." data-loc="'+esc(loc.location_id)+'" data-idx="'+j+'" cx="'+pts[j][0].toFixed(1)+'" cy="'+pts[j][1].toFixed(1)+'" r="10.5" fill="'+fill+'" stroke="'+stroke+'" stroke-width="2" style="cursor:pointer;"></circle>');
    parts.push('<text x="'+pts[j][0].toFixed(1)+'" y="'+(pts[j][1]+1).toFixed(1)+'" text-anchor="middle" dominant-baseline="central" font-family="var(--font-mono)" font-size="9.5" font-weight="700" fill="'+textFill+'" pointer-events="none">'+j+'</text>');
  }
  $("dynamicLayer").innerHTML = parts.join("");
  updateProgressUI();
  wireNodeInteractions();
}

/* ---------------- picker animation + playback ---------------- */
function setPickerPos(x,y){ var g=$("pickerGroup"); if(g) g.setAttribute("transform","translate("+x.toFixed(1)+","+y.toFixed(1)+")"); }
function snapPicker(idx){ var l=state.fullPath[idx]; if(!l) return; var p=worldToScreen(l.x,l.y); setPickerPos(p[0],p[1]); }
function reducedMotion(){ return window.matchMedia && window.matchMedia("(prefers-reduced-motion: reduce)").matches; }
function animatePicker(from,to,done){
  var p1=worldToScreen(from.x,from.y), p2=worldToScreen(to.x,to.y);
  if (reducedMotion()){ setPickerPos(p2[0],p2[1]); done&&done(); return; }
  var start=performance.now(), dur=650;
  function frame(now){
    var t=Math.min(1,(now-start)/dur);
    var e=t<0.5?4*t*t*t:1-Math.pow(-2*t+2,3)/2;
    setPickerPos(p1[0]+(p2[0]-p1[0])*e, p1[1]+(p2[1]-p1[1])*e);
    if(t<1) state.animFrame=requestAnimationFrame(frame); else done&&done();
  }
  state.animFrame=requestAnimationFrame(frame);
}
function isAtStart(){ return state.currentStepIndex<=0; }
function isAtEnd(){ return state.currentStepIndex>=state.fullPath.length-1; }
function clearTimers(){ if(state.playTimer){clearTimeout(state.playTimer);state.playTimer=null;} if(state.animFrame){cancelAnimationFrame(state.animFrame);state.animFrame=null;} }
function setPlayIcon(playing){
  $("playBtn").setAttribute("aria-label", playing ? "Pause route" : "Play route");
  $("playBtn").setAttribute("title", playing ? "Pause route" : "Play route");
  $("playIcon").innerHTML = playing
    ? '<rect x="5" y="3" width="4.5" height="18" rx="1"></rect><rect x="14.5" y="3" width="4.5" height="18" rx="1"></rect>'
    : '<polygon points="6 3 20 12 6 21 6 3"></polygon>';
}
function updatePlaybackButtons(){
  $("stepBackBtn").disabled=isAtStart(); $("stepFwdBtn").disabled=isAtEnd(); $("playBtn").disabled=isAtEnd();
  setPlayIcon(state.isPlaying);
}
function updateProgressUI(){
  var n=state.fullPath.length-2;
  var completed=Math.min(Math.max(state.currentStepIndex,0),n);
  var pct = state.fullPath.length>1 ? (Math.min(state.currentStepIndex,state.fullPath.length-1)/(state.fullPath.length-1))*100 : 0;
  var fill=$("progressFill"); fill.style.width=pct+"%"; fill.classList.toggle("done", isAtEnd());
  $("progressLabel").textContent = isAtEnd() ? "Done \u2014 "+n+"/"+n : completed+" / "+n;
}
function stepForward(done){
  if (isAtEnd()) return;
  var i=state.currentStepIndex, j=i+1;
  animatePicker(state.fullPath[i], state.fullPath[j], function(){
    state.currentStepIndex=j; renderDynamicLayer(); updatePlaybackButtons(); done&&done();
  });
}
function stepBack(){
  pause(); if (isAtStart()) return;
  var i=state.currentStepIndex, j=i-1;
  animatePicker(state.fullPath[i], state.fullPath[j], function(){
    state.currentStepIndex=j; renderDynamicLayer(); updatePlaybackButtons();
  });
}
function advanceLoop(){
  if (!state.isPlaying) return;
  if (isAtEnd()){ state.isPlaying=false; updatePlaybackButtons(); return; }
  stepForward(function(){
    if (state.isPlaying && !isAtEnd()) state.playTimer=setTimeout(advanceLoop,320);
    else { state.isPlaying=false; updatePlaybackButtons(); }
  });
}
function play(){ if (isAtEnd()) return; state.isPlaying=true; updatePlaybackButtons(); advanceLoop(); }
function pause(){ state.isPlaying=false; clearTimers(); updatePlaybackButtons(); }
function resetPlayback(){ pause(); state.currentStepIndex=0; renderDynamicLayer(); snapPicker(0); updatePlaybackButtons(); }

/* ---------------- selection ---------------- */
function buildFullPath(batch, algo){
  var ids=[DEPOT_ID].concat(batch.routes[algo].sequence).concat([DEPOT_ID]);
  return ids.map(function(id){ return locationById[id]; });
}
function applySelection(opts){
  var autoPlay = opts && opts.autoPlay;
  var batch = C.batchesById[state.selectedBatchId];
  if (!batch) return;
  pause();
  state.fullPath = buildFullPath(batch, state.selectedAlgo);
  state.currentStepIndex = 0;
  renderDynamicLayer(); snapPicker(0);
  $("statOrders").textContent = batch.num_orders;
  $("statWeight").textContent = batch.total_weight_kg.toFixed(2)+" kg";
  $("statStops").textContent = batch.num_stops;
  $("statTime").textContent = batch.routes[state.selectedAlgo].time_min.toFixed(1)+" min";
  $("mapSubtitle").textContent = batch.batch_id+" \u2014 stored picker route (sample data)";
  $("algoBadge").textContent = C.ALGO_LABELS[state.selectedAlgo].toUpperCase();
  $("routeText").textContent = "Route for " + batch.batch_id + " using " + C.ALGO_LABELS[state.selectedAlgo] + ": " +
    state.fullPath.map(function(l){ return l.location_id; }).join(", then ") + ". Distance " +
    batch.routes[state.selectedAlgo].distance_m.toFixed(1) + " metres (sample data).";
  updatePlaybackButtons();
  $("selectedNode").classList.remove("visible");
  if (autoPlay) play();
}

/* ---------------- tooltip + selected node ---------------- */
function wireNodeInteractions(){
  var tooltip = $("nodeTooltip");
  document.querySelectorAll("#dynamicLayer .stop-node").forEach(function(node){
    node.addEventListener("mouseenter", function(e){ showTooltip(e, node.dataset.loc); });
    node.addEventListener("mousemove", function(e){ positionTooltip(e); });
    node.addEventListener("mouseleave", function(){ tooltip.style.opacity=0; });
    node.addEventListener("click", function(){ showSelectedNode(node.dataset.loc, node.dataset.idx); });
    node.addEventListener("keydown", function(e){
      if (e.key==="Enter" || e.key===" "){ e.preventDefault(); showSelectedNode(node.dataset.loc, node.dataset.idx); }
    });
  });
  function showTooltip(e, locId){
    var loc = locationById[locId];
    tooltip.innerHTML = '<div class="tt-title">'+esc(locId)+'</div><div class="tt-row">Aisle '+esc(loc.aisle||"-")+'</div>';
    tooltip.style.opacity = 1;
    positionTooltip(e);
  }
  function positionTooltip(e){
    var wrap = $("mapWrap").getBoundingClientRect();
    tooltip.style.left = (e.clientX - wrap.left + 14) + "px";
    tooltip.style.top = (e.clientY - wrap.top - 10) + "px";
  }
}
function showSelectedNode(locId, idx){
  var loc = locationById[locId];
  var el = $("selectedNode");
  el.innerHTML = '<div class="sn-title">Stop '+esc(idx)+' \u2014 '+esc(locId)+'</div><div class="sn-row">Aisle '+esc(loc.aisle||"-")+' &middot; x='+esc(loc.x)+', y='+esc(loc.y)+'</div>';
  el.classList.add("visible");
}

/* ---------------- pan / zoom / fullscreen ---------------- */
function clampZoom(z){ return Math.max(0.6, Math.min(4, z)); }
function wireMapControls(){
  var svg=$("warehouseMap"), wrap=$("mapWrap");
  svg.addEventListener("wheel", function(e){
    e.preventDefault();
    var delta = e.deltaY>0 ? -0.12 : 0.12;
    state.zoom = clampZoom(state.zoom+delta);
    applyViewportTransform();
  }, {passive:false});

  svg.addEventListener("pointerdown", function(e){
    if (e.target && e.target.classList && e.target.classList.contains("stop-node")) return;
    state.isPanning=true; state.panStart={x:e.clientX,y:e.clientY,panX:state.panX,panY:state.panY};
    svg.classList.add("is-panning"); svg.setPointerCapture(e.pointerId);
  });
  svg.addEventListener("pointermove", function(e){
    if (!state.isPanning) return;
    state.panX = state.panStart.panX + (e.clientX-state.panStart.x);
    state.panY = state.panStart.panY + (e.clientY-state.panStart.y);
    applyViewportTransform();
  });
  ["pointerup","pointerleave"].forEach(function(ev){
    svg.addEventListener(ev, function(){ state.isPanning=false; svg.classList.remove("is-panning"); });
  });

  svg.addEventListener("keydown", function(e){
    var step = 30, handled = true;
    if (e.key==="ArrowLeft") state.panX += step;
    else if (e.key==="ArrowRight") state.panX -= step;
    else if (e.key==="ArrowUp") state.panY += step;
    else if (e.key==="ArrowDown") state.panY -= step;
    else if (e.key==="+" || e.key==="=") state.zoom = clampZoom(state.zoom+0.25);
    else if (e.key==="-" || e.key==="_") state.zoom = clampZoom(state.zoom-0.25);
    else if (e.key==="0") { state.zoom=1; state.panX=0; state.panY=0; }
    else handled = false;
    if (handled){ e.preventDefault(); applyViewportTransform(); }
  });

  $("zoomInBtn").addEventListener("click", function(){ state.zoom=clampZoom(state.zoom+0.25); applyViewportTransform(); });
  $("zoomOutBtn").addEventListener("click", function(){ state.zoom=clampZoom(state.zoom-0.25); applyViewportTransform(); });
  $("resetViewBtn").addEventListener("click", function(){ state.zoom=1; state.panX=0; state.panY=0; applyViewportTransform(); });
  $("fullscreenBtn").addEventListener("click", function(){
    if (!document.fullscreenElement) wrap.requestFullscreen ? wrap.requestFullscreen() : null;
    else document.exitFullscreen();
  });
  document.addEventListener("fullscreenchange", function(){
    wrap.classList.toggle("is-fullscreen", !!document.fullscreenElement);
  });
}

window.__APP__.mapState = state;
window.__APP__.setupMapScale = setupMapScale;
window.__APP__.renderMapSkeleton = renderMapSkeleton;
window.__APP__.renderStaticMap = renderStaticMap;
window.__APP__.initPickerLayer = initPickerLayer;
window.__APP__.applySelection = applySelection;
window.__APP__.wireMapControls = wireMapControls;
window.__APP__.playbackFns = {play:play, pause:pause, stepForward:stepForward, stepBack:stepBack, resetPlayback:resetPlayback};
})();
(function(){
"use strict";
var C = window.__APP__;
var DATA=C.DATA, $=C.$, esc=C.esc, fmtM=C.fmtM, fmtPct=C.fmtPct;

function renderDistanceChart(){
  var before=DATA.meta.distance_baseline_m, after=DATA.meta.distance_optimized_m;
  var maxVal=Math.max(before,after,1);
  var vw=420, vh=210, baseline=176, maxH=126, barW=84, gap=64;
  var totalW=barW*2+gap, startX=(vw-totalW)/2;
  var x1=startX, x2=startX+barW+gap;
  var h1=(before/maxVal)*maxH, h2=(after/maxVal)*maxH;
  var y1=baseline-h1, y2=baseline-h2;
  var cx1=x1+barW/2, cx2=x2+barW/2;
  var svg='<svg viewBox="0 0 '+vw+' '+vh+'" width="100%" role="img" aria-label="Distance before '+Math.round(before)+' meters versus after '+Math.round(after)+' meters">'+
    '<line x1="20" y1="'+baseline+'" x2="'+(vw-20)+'" y2="'+baseline+'" stroke="var(--border)" stroke-width="1"></line>'+
    '<rect x="'+x1.toFixed(1)+'" y="'+y1.toFixed(1)+'" width="'+barW+'" height="'+h1.toFixed(1)+'" rx="4" fill="var(--surface-2)"></rect>'+
    '<rect x="'+x2.toFixed(1)+'" y="'+y2.toFixed(1)+'" width="'+barW+'" height="'+h2.toFixed(1)+'" rx="4" fill="var(--green)"></rect>'+
    '<text x="'+cx1.toFixed(1)+'" y="'+(y1-10).toFixed(1)+'" text-anchor="middle" font-family="var(--font-mono)" font-size="13" font-weight="600" fill="var(--text-primary)">'+fmtM(before)+'</text>'+
    '<text x="'+cx2.toFixed(1)+'" y="'+(y2-10).toFixed(1)+'" text-anchor="middle" font-family="var(--font-mono)" font-size="13" font-weight="600" fill="var(--green)">'+fmtM(after)+'</text>'+
    '<text x="'+cx1.toFixed(1)+'" y="'+(baseline+20)+'" text-anchor="middle" font-size="11" fill="var(--text-secondary)">Before</text>'+
    '<text x="'+cx2.toFixed(1)+'" y="'+(baseline+20)+'" text-anchor="middle" font-size="11" fill="var(--text-secondary)">After</text>'+
    '<text x="'+(vw/2)+'" y="22" text-anchor="middle" font-family="var(--font-mono)" font-size="12" font-weight="600" fill="var(--green)">\u2212'+fmtPct(DATA.meta.improvement_pct)+'</text>'+
    '</svg>';
  $("chartDistance").innerHTML = svg;
}

function renderAlgoChart(){
  var vals=[{label:"Greedy",v:C.greedyTotal,color:"var(--surface-2)",textColor:"var(--text-secondary)"},
            {label:"Nearest neighbor",v:C.nnTotal,color:"#2A3B5C",textColor:"#8FAEE0"},
            {label:"2-opt",v:C.twoOptTotal,color:"var(--blue)",textColor:"var(--blue-text)"}];
  var vw=420, vh=210, marginTop=26, marginBottom=40, baseline=vh-marginBottom, maxH=vh-marginTop-marginBottom;
  var maxVal=Math.max.apply(null,vals.map(function(d){return d.v;}))||1;
  var barW=70, gap=32, totalW=vals.length*barW+(vals.length-1)*gap, startX=(vw-totalW)/2;
  var parts=['<line x1="20" y1="'+baseline+'" x2="'+(vw-20)+'" y2="'+baseline+'" stroke="var(--border)" stroke-width="1"></line>'];
  vals.forEach(function(d,i){
    var x=startX+i*(barW+gap), h=(d.v/maxVal)*maxH, y=baseline-h, cx=x+barW/2;
    parts.push('<rect x="'+x.toFixed(1)+'" y="'+y.toFixed(1)+'" width="'+barW+'" height="'+h.toFixed(1)+'" rx="4" fill="'+d.color+'"></rect>');
    parts.push('<text x="'+cx.toFixed(1)+'" y="'+(y-9).toFixed(1)+'" text-anchor="middle" font-family="var(--font-mono)" font-size="12" font-weight="600" fill="'+d.textColor+'">'+fmtM(d.v)+'</text>');
    parts.push('<text x="'+cx.toFixed(1)+'" y="'+(baseline+18)+'" text-anchor="middle" font-size="10.5" fill="var(--text-secondary)">'+esc(d.label)+'</text>');
  });
  $("chartAlgo").innerHTML = '<svg viewBox="0 0 '+vw+' '+vh+'" width="100%" role="img" aria-label="Total distance by algorithm">'+parts.join("")+'</svg>';
}

function renderHeatmap(){
  var list=C.aisleList.slice().sort(function(a,b){ return a.aisle.localeCompare(b.aisle); });
  var maxCount=Math.max.apply(null,list.map(function(d){return d.count;}))||1;
  var vw=420, rowH=26, gap=8, marginLeft=44, marginRight=54, marginTop=8;
  var vh=marginTop+list.length*(rowH+gap);
  var barMaxW=vw-marginLeft-marginRight;
  var parts=[];
  list.forEach(function(d,i){
    var y=marginTop+i*(rowH+gap);
    var w=(d.count/maxCount)*barMaxW;
    var intensity = 0.25 + 0.65*(d.count/maxCount);
    parts.push('<text x="'+(marginLeft-8)+'" y="'+(y+rowH/2+1)+'" text-anchor="end" dominant-baseline="central" font-family="var(--font-mono)" font-size="10.5" fill="var(--text-secondary)">'+esc(d.aisle)+'</text>');
    parts.push('<rect x="'+marginLeft+'" y="'+y+'" width="'+barMaxW+'" height="'+rowH+'" rx="4" fill="var(--surface-2)"></rect>');
    parts.push('<rect x="'+marginLeft+'" y="'+y+'" width="'+Math.max(2,w).toFixed(1)+'" height="'+rowH+'" rx="4" fill="var(--blue)" opacity="'+intensity.toFixed(2)+'"></rect>');
    parts.push('<text x="'+(marginLeft+barMaxW+8)+'" y="'+(y+rowH/2+1)+'" dominant-baseline="central" font-family="var(--font-mono)" font-size="10.5" font-weight="600" fill="var(--text-primary)">'+d.count+'</text>');
  });
  $("chartHeatmap").innerHTML = '<svg viewBox="0 0 '+vw+' '+vh+'" width="100%" role="img" aria-label="Pick stops per aisle">'+parts.join("")+'</svg>';
}

function renderEfficiencyChart(){
  var data=C.savedPerBatch;
  var vw=420, vh=210, marginLeft=8, marginRight=8, marginTop=10, marginBottom=34;
  var innerW=vw-marginLeft-marginRight, innerH=vh-marginTop-marginBottom;
  var n=Math.max(1,data.length), gap=3;
  var barW=Math.max(4,Math.min(20,(innerW-(n-1)*gap)/n));
  var usedW=n*barW+(n-1)*gap, startX=marginLeft+(innerW-usedW)/2;
  var maxVal=Math.max.apply(null,data.map(function(d){return d.saved;}))||1;
  var labelEvery = n<=12?1:Math.ceil(n/8);
  var bars="", labels="";
  data.forEach(function(d,i){
    var x=startX+i*(barW+gap), h=Math.max(2,(d.saved/maxVal)*innerH), y=marginTop+innerH-h, cx=x+barW/2;
    bars+='<rect x="'+x.toFixed(1)+'" y="'+y.toFixed(1)+'" width="'+barW.toFixed(1)+'" height="'+h.toFixed(1)+'" rx="2.5" fill="var(--green)"><title>'+esc(d.batch_id)+': '+d.saved.toFixed(1)+' m ('+d.pct.toFixed(1)+'%)</title></rect>';
    if (i%labelEvery===0 || i===n-1){
      labels+='<text x="'+cx.toFixed(1)+'" y="'+(marginTop+innerH+15)+'" text-anchor="middle" font-family="var(--font-mono)" font-size="8.5" fill="var(--text-muted)">'+esc(d.batch_id.replace("BATCH-",""))+'</text>';
    }
  });
  $("chartEfficiency").innerHTML = '<svg viewBox="0 0 '+vw+' '+vh+'" width="100%" role="img" aria-label="Distance saved per batch across '+n+' batches"><line x1="'+marginLeft+'" y1="'+(marginTop+innerH)+'" x2="'+(vw-marginRight)+'" y2="'+(marginTop+innerH)+'" stroke="var(--border)" stroke-width="1"></line>'+bars+labels+'</svg>';
}

/* ---------------- insights (rule-based, computed from real stats) ---------------- */
var CHECK='';
var WARN='';

function renderInsights(){
  var m=DATA.meta;
  var items=[];
  items.push({icon:CHECK, text:"In this sample run, total distance was "+fmtPct(m.improvement_pct)+" lower than the unoptimized baseline (FFD batching + greedy routing)."});
  items.push({icon:CHECK, text:fmtM(m.distance_saved_m)+" less walking across "+m.batches_optimized+" batches ("+fmtM(m.distance_baseline_m)+" \u2192 "+fmtM(m.distance_optimized_m)+")."});
  if (C.bestBatch && C.bestBatch.batch_id) items.push({icon:CHECK, text:C.bestBatch.batch_id+" had the largest single-batch reduction, "+fmtPct(C.bestBatch.pct)+" shorter than its greedy route."});
  items.push({icon:CHECK, text:"Average 2-opt route length is "+Math.round(C.avgRouteLength)+" m per batch, with an estimated "+C.avgPickTimeMin.toFixed(1)+" min of picker time (based on assumed walking speed and per-stop pick time)."});
  items.push({icon:CHECK, text:"Backend runtime for this run was "+m.runtime_sec.toFixed(1)+" s for "+m.orders_processed+" sample orders. Runtime on other data or hardware will differ."});
  if (C.busiestAisle && C.quietestAisle && C.busiestAisle.count > C.quietestAisle.count*1.5){
    items.push({icon:WARN, text:"Aisle "+C.busiestAisle.aisle+" has "+C.busiestAisle.count+" pick stops versus "+C.quietestAisle.count+" in aisle "+C.quietestAisle.aisle+" in this sample. Aisle congestion is not modeled by this project."});
  } else if (C.busiestAisle && C.busiestAisle.aisle){
    items.push({icon:CHECK, text:"Pick stops are fairly evenly spread across aisles in this sample (most: aisle "+C.busiestAisle.aisle+", "+C.busiestAisle.count+" stops)."});
  }
  $("insightsList").innerHTML = "<ul class=\"run-notes\">" + items.map(function(it){
    return '<li>'+esc(it.text)+'</li>';
  }).join("") + "</ul>";
}

window.__APP__.renderCharts = function(){
  renderDistanceChart(); renderAlgoChart(); renderHeatmap(); renderEfficiencyChart();
};
window.__APP__.renderInsights = renderInsights;
})();
(function(){
"use strict";
var C = window.__APP__;
var DATA=C.DATA, $=C.$, esc=C.esc;

var COLUMNS = [
  {key:"batch_id", label:"Batch", type:"str"},
  {key:"num_orders", label:"Orders", type:"num"},
  {key:"num_stops", label:"Stops", type:"num"},
  {key:"total_weight_kg", label:"Weight (kg)", type:"num"},
  {key:"distance_m", label:"Distance (m)", type:"num"},
  {key:"time_min", label:"Time (min)", type:"num"},
  {key:"pct_saved", label:"vs. greedy", type:"num"}
];

var tableState = {sortKey:"batch_id", sortDir:1, search:"", page:1, pageSize:10};

function tableRows(){
  return DATA.batches.map(function(b){
    var r2 = b.routes.two_opt, rg = b.routes.greedy;
    var saved = rg.distance_m - r2.distance_m;
    var pct = rg.distance_m>0 ? (saved/rg.distance_m)*100 : 0;
    return {
      batch_id:b.batch_id, num_orders:b.num_orders, num_stops:b.num_stops,
      total_weight_kg:b.total_weight_kg, distance_m:r2.distance_m, time_min:r2.time_min,
      pct_saved: pct
    };
  });
}

function filteredSorted(){
  var rows = tableRows();
  if (tableState.search){
    var q = tableState.search.toLowerCase();
    rows = rows.filter(function(r){ return r.batch_id.toLowerCase().indexOf(q) !== -1; });
  }
  var key=tableState.sortKey, dir=tableState.sortDir;
  rows.sort(function(a,b){
    var av=a[key], bv=b[key];
    if (typeof av === "string") return av.localeCompare(bv) * dir;
    return (av-bv) * dir;
  });
  return rows;
}

function renderTableHead(){
  var html = COLUMNS.map(function(c){
    var sorted = tableState.sortKey===c.key;
    var arrow = sorted ? (tableState.sortDir===1?"\u25B2":"\u25BC") : "\u25B2";
    return '<th scope="col" class="'+(sorted?"sorted":"")+'" data-key="'+c.key+'" aria-sort="'+(sorted?(tableState.sortDir===1?"ascending":"descending"):"none")+'"><button type="button">'+esc(c.label)+'<span class="sort-arrow" aria-hidden="true">'+arrow+'</span></button></th>';
  }).join("");
  $("tableHead").innerHTML = html;
  document.querySelectorAll("#tableHead th").forEach(function(th){
    th.querySelector("button").addEventListener("click", function(){
      var key = th.dataset.key;
      if (tableState.sortKey===key) tableState.sortDir *= -1;
      else { tableState.sortKey=key; tableState.sortDir=1; }
      tableState.page=1;
      renderTable();
      var again = document.querySelector('#tableHead th[data-key="'+key+'"] button');
      if (again) again.focus();
    });
  });
}

function renderTableBody(){
  var rows = filteredSorted();
  var totalPages = Math.max(1, Math.ceil(rows.length/tableState.pageSize));
  tableState.page = Math.min(tableState.page, totalPages);
  var start = (tableState.page-1)*tableState.pageSize;
  var pageRows = rows.slice(start, start+tableState.pageSize);

  $("tableBody").innerHTML = pageRows.map(function(r){
    return '<tr>' +
      '<td style="font-family:var(--font-mono);">'+esc(r.batch_id)+'</td>' +
      '<td class="tnum">'+r.num_orders+'</td>' +
      '<td class="tnum">'+r.num_stops+'</td>' +
      '<td class="tnum">'+r.total_weight_kg.toFixed(2)+'</td>' +
      '<td class="tnum">'+Math.round(r.distance_m)+'</td>' +
      '<td class="tnum">'+r.time_min.toFixed(1)+'</td>' +
      '<td class="tnum pct-cell">'+r.pct_saved.toFixed(1)+'%</td>' +
      '</tr>';
  }).join("");

  $("tableCount").textContent = rows.length + (rows.length===1?" batch":" batches") + (tableState.search?" (filtered)":"");
  $("pageLabel").textContent = tableState.page + " / " + totalPages;
  $("pagePrev").disabled = tableState.page<=1;
  $("pageNext").disabled = tableState.page>=totalPages;
}

function renderTable(){ renderTableHead(); renderTableBody(); }

function csvCell(v){
  var t = String(v);
  if (/^[=+\-@\t\r]/.test(t)) t = "'" + t;          // avoid formula injection in Excel/Sheets
  return /[",\n]/.test(t) ? '"' + t.replace(/"/g,'""') + '"' : t;
}
function exportCSV(){
  var rows = filteredSorted();
  var header = COLUMNS.map(function(c){return c.label;}).join(",");
  var lines = rows.map(function(r){
    return [r.batch_id, r.num_orders, r.num_stops, r.total_weight_kg.toFixed(2), Math.round(r.distance_m), r.time_min.toFixed(1), r.pct_saved.toFixed(1)].map(csvCell).join(",");
  });
  var csv = header + "\n" + lines.join("\n");
  var blob = new Blob([csv], {type:"text/csv"});
  var url = URL.createObjectURL(blob);
  var a = document.createElement("a");
  a.href = url; a.download = "batch_details_SAMPLE_DATA.csv";
  document.body.appendChild(a); a.click(); document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

window.__APP__.renderTable = renderTable;
window.__APP__.exportCSV = exportCSV;
window.__APP__.tableState = tableState;

/* ==================================================================== */
/* Init + top-level wiring                                              */
/* ==================================================================== */

function populateBatchSelect(){
  var sel = $("batchSelect");
  sel.innerHTML = DATA.batches.map(function(b){
    return '<option value="'+esc(b.batch_id)+'">'+esc(b.batch_id)+' \u2014 '+esc(b.num_orders)+' order'+(b.num_orders===1?"":"s")+', '+esc(b.num_stops)+' stops</option>';
  }).join("");
  C.mapState.selectedBatchId = DATA.batches[0].batch_id;
  sel.value = C.mapState.selectedBatchId;
}

function onOptimizeClick(){
  var btn = $("optimizeBtn");
  var original = btn.innerHTML;
  btn.disabled = true;
  btn.textContent = "Replaying\u2026";
  setTimeout(function(){
    C.applySelection({autoPlay:true});
    btn.disabled = false;
    btn.innerHTML = original;
  }, 450);
}

function wireEvents(){
  $("batchSelect").addEventListener("change", function(e){
    C.mapState.selectedBatchId = e.target.value;
    C.applySelection({autoPlay:false});
  });
  document.querySelectorAll("#algoSegmented button").forEach(function(btn){
    btn.addEventListener("click", function(){
      document.querySelectorAll("#algoSegmented button").forEach(function(b){ b.classList.remove("active"); b.setAttribute("aria-pressed","false"); });
      btn.classList.add("active"); btn.setAttribute("aria-pressed","true");
      C.mapState.selectedAlgo = btn.dataset.algo;
      C.applySelection({autoPlay:false});
    });
  });
  $("optimizeBtn").addEventListener("click", onOptimizeClick);
  $("playBtn").addEventListener("click", function(){ C.mapState.isPlaying ? C.playbackFns.pause() : C.playbackFns.play(); });
  $("stepFwdBtn").addEventListener("click", function(){ C.playbackFns.pause(); C.playbackFns.stepForward(); });
  $("stepBackBtn").addEventListener("click", C.playbackFns.stepBack);
  $("resetBtn").addEventListener("click", C.playbackFns.resetPlayback);

  $("exportBtn").addEventListener("click", C.exportCSV);

  $("tableSearch").addEventListener("input", function(e){
    C.tableState.search = e.target.value;
    C.tableState.page = 1;
    C.renderTable();
  });
  $("pagePrev").addEventListener("click", function(){ C.tableState.page = Math.max(1, C.tableState.page-1); C.renderTable(); });
  $("pageNext").addEventListener("click", function(){ C.tableState.page += 1; C.renderTable(); });

  C.wireMapControls();
}

function init(){
  if (window.__DASHBOARD_DATA_MISSING__) return; // empty-state message already rendered
  $("genTime").textContent = "Sample results generated " + C.fmtTime(DATA.meta.generated_at);
  C.setupMapScale();
  C.renderMapSkeleton();
  C.renderStaticMap();
  C.initPickerLayer();
  populateBatchSelect();
  C.renderKPIs();
  C.renderCharts();
  C.renderInsights();
  C.renderTable();
  wireEvents();
  C.applySelection({autoPlay:false});
}

document.addEventListener("DOMContentLoaded", init);
})();
